version: 2
jobs:
  build:
    machine: true
    working_directory: ~/learn-circleci
    steps:
    - checkout
    - run: pwd
    - run: ls -l
    - run: sh ./build.sh
  deploy:
    machine:
      enabled: true
    steps:
    - run:
        name: Deploy Over SSH
        command: if [ "${CIRCLE_BRANCH}" == "master" ]; then ssh wcn@47.100.104.10 'cd /home/wcn && . deploy-circleci.sh'; else echo "Skipped"; fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
