version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7

workflows:
  "Hello Workflow":
    jobs:
    - hello/hello-build

environment:
   SERVER_IP_ADDRESS: 47.100.104.10
   DOKKU_APP: circlecidemo
   TRAVIS: "false"

